import argparse

def get_default_args():
    argparser = argparse.ArgumentParser()
    # run settings
    argparser.add_argument('--data_path', type=str, default='./data/babi(tmp).pkl')
    argparser.add_argument('--model_name', type=str, default='m')
    argparser.add_argument('--checkpoint_dir', type=str, default='./results/')
    argparser.add_argument('--batch_size', type=int, default=32)
    argparser.add_argument('--epoch', type=int, default=100)
    argparser.add_argument('--train', type=int, default=1)
    argparser.add_argument('--valid', type=int, default=1)
    argparser.add_argument('--test', type=int, default=1)
    argparser.add_argument('--early_stop', type=int, default=0)
    argparser.add_argument('--resume', action='store_true', default=False)
    argparser.add_argument('--save', action='store_true', default=False)
    argparser.add_argument('--print_step', type=float, default=128)

    # model hyperparameters
    argparser.add_argument('--lr', type=float, default=0.0003)
    argparser.add_argument('--lr_decay', type=float, default=1.0)
    argparser.add_argument('--wd', type=float, default=0)
    argparser.add_argument('--grad_max_norm', type=int, default=5)
    argparser.add_argument('--s_rnn_hidden_dim', type=int, default=100)
    argparser.add_argument('--s_cnn_k', type=int, default=3)
    argparser.add_argument('--s_rnn_layer_num', type=int, default=1)
    argparser.add_argument('--s_rnn_dr', type=float, default=0.0)
    argparser.add_argument('--q_rnn_hidden_dim', type=int, default=100)
    argparser.add_argument('--q_cnn_k', type=int, default=3)
    argparser.add_argument('--q_rnn_layer_num', type=int, default=1)
    argparser.add_argument('--q_rnn_dr', type=float, default=0.0)
    argparser.add_argument('--e_cell_hidden_dim', type=int, default=100)
    argparser.add_argument('--m_cell_hidden_dim', type=int, default=100)
    argparser.add_argument('--a_cell_hidden_dim', type=int, default=100)
    argparser.add_argument('--word_dr', type=float, default=0.2)
    argparser.add_argument('--g1_dim', type=int, default=500)
    argparser.add_argument('--max_episode', type=int, default=10)
    argparser.add_argument('--beta_cnt', type=int, default=10)
    argparser.add_argument('--set_num', type=int, default=1)
    argparser.add_argument('--max_alen', type=int, default=2)
    return argparser.parse_args()
